/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Draft': RouteRecordInfo<'/Draft', '/Draft', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Implementation': RouteRecordInfo<'/Implementation', '/Implementation', Record<never, never>, Record<never, never>>,
    '/Person': RouteRecordInfo<'/Person', '/Person', Record<never, never>, Record<never, never>>,
    '/Product': RouteRecordInfo<'/Product', '/Product', Record<never, never>, Record<never, never>>,
  }
}
